CREATE DATABASE IF NOT EXISTS drinkdb;

USE drinkdb;

DROP TABLE IF EXISTS drinks;
CREATE TABLE drinks(
    drink_id int,
    drink varchar(64),
    ingredients varchar(1024),
    method varchar(1024)
);

DROP TABLE IF EXISTS ingredients;
CREATE TABLE ingredients(
    drink_id int,
    ingredient varchar(64)
);

DROP TABLE IF EXISTS ratings;
CREATE TABLE ratings(
    drink_id int,
    likes int,
    dislikes int
);

INSERT INTO drinks VALUE(0, "Bellini", "100 ml Prosecco,50 ml White Peach Puree", "Pour peach puree into the mixing glass with ice, add the Prosecco wine. Stir gently and pour in a chilled flute glass.  Note: PUCCINI - Fresh Mandarin Orange Juice; ROSSINI - Fresh Strawberry Puree; TINTORETTO - Fresh Pomegranate Juice.");
INSERT INTO drinks VALUE(1, "Black Russian", "50 ml Vodka,20 ml Coffee Liqueur", "Pour the ingredients into the old fashioned glass filled with ice cubes. Stir gently.  Note: WHITE RUSSIAN - Float fresh cream on the top and stir in slowly.");
INSERT INTO drinks VALUE(2, "Bloody Mary", "45 ml Vodka,90 ml Tomato Juice,15 ml Fresh Lemon Juice,2 dashes Worcestershire Sauce,Tabasco,Celery Salt,Pepper (Up to taste)", "Stir gently all the ingredients in a mixing glass with ice, pour into rocks glass. Note: If requested served with ice, pour into highball glass.");
INSERT INTO drinks VALUE(3, "Caipirinha", "60 ml Cachaça,1 Lime cut into small wedges,4 Teaspoons White Cane Sugar", "Place lime and sugar into a double old fashioned glass and muddle gently. Fill the glass with cracked ice and add Cachaça. Stir gently to involve ingredients. Note: CAIPIROSKA - Instead of Cachaça use Vodka;");
INSERT INTO drinks VALUE(4, "Champagne Cocktail", "90 ml Chilled Champagne,10 ml Cognac,2 dashes Angostura bitters,Few drops of Grand Marnier (optional),1 sugar cube", "Place the sugar cube with 2 dashes of bitters in a large Champagne glass, add the cognac. Pour gently chilled Champagne.");
INSERT INTO drinks VALUE(5, "Corpse Reviver #2", "30 ml Gin,30 ml Cointreau,30 ml Lillet Blanc,30 ml Fresh Lemon Juice,1 dash Absinthe", "Pour all ingredients into shaker with ice. Shake well and strain in chilled cocktail glass.");
INSERT INTO drinks VALUE(6, "Cosmopolitan", "40 ml Vodka Citron,15 ml Cointreau,15 ml Fresh Lime Juice,30 ml Cranberry Juice", "Add all ingredients into a cocktail shaker filled with ice. Shake well and strain into a large cocktail glass.");
INSERT INTO drinks VALUE(7, "Cuba Libre", "50 ml White Rum,120 ml Coca Cola,10 ml Fresh Lime Juice", "Build all ingredients in a highball glass filled with ice.");
INSERT INTO drinks VALUE(8, "French 75", "30 ml Gin,15 ml Fresh Lemon Juice,15 ml Sugar Syrup,60 ml Champagne", "Pour all the ingredients, except Champagne, into a shaker. Shake well and strain into a Champagne flute. Top up with Champagne. Stir gently.");
INSERT INTO drinks VALUE(9, "French Connection", "35 ml Cognac,35 ml Amaretto", "Pour all ingredients directly into an old fashioned glass filled with ice cubes. Stir gently.");
INSERT INTO drinks VALUE(10, "Golden Dream", "20 ml Galliano,20 ml Triple Sec,20 ml Fresh Orange Juice,10 ml Fresh Cream", "Pour all ingredients into shaker filled with ice. Shake briskly for few seconds. Strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(11, "Grasshopper", "20 ml Crème de Cacao (White),20 ml Crème de Menthe (Green),20 ml Fresh Cream", "Pour all ingredients into shaker filled with ice. Shake briskly for few seconds. Strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(12, "Hemingway Special", "60 ml Rum,40 ml Grapefruit Juice,15 ml Maraschino Luxardo,15 ml Fresh Lime", "Pour all ingredients into a shaker with ice. Shake well and strain into a large cocktail glass.");
INSERT INTO drinks VALUE(13, "Horse's Neck", "40 ml Cognac,120 ml Ginger Ale,Dash of Angostura Bitters (optional)", "Pour Cognac and ginger ale directly into a highball glass with ice cubes. Stir gently. If preferred, add dashes of Angostura Bitter.");
INSERT INTO drinks VALUE(14, "Irish Coffee", "50 ml Irish Whiskey,120 ml Hot coffee,50 ml Fresh cream (Chilled),1 teaspoon Sugar", "Warm black coffee is poured into a pre-heated Irish coffee glass. Whiskey and at least one teaspoon of sugar is added and stirred until dissolved. Fresh thick chilled cream is carefully poured over the back of a spoon held just above the surface of the coffee. The layer of cream will float on the coffee without mixing. Plain sugar can be replaced with sugar syrup");
INSERT INTO drinks VALUE(15, "KIR", "90 ml Dry White Wine,10 ml Crème de Cassis", "Pour Crème de Cassis into glass, top up with white wine. Note: KIR ROYAL - Use Champagne instead of white wine");
INSERT INTO drinks VALUE(16, "Long Island Ice Tea", "15 ml Vodka,15 ml Tequila,15 ml White rum,15 ml Gin,15 ml Cointreau,30 ml Lemon juice,20 ml Simple syrup,Top with Cola", "Add all ingredients into a highball glass filled with ice. Stir gently.");
INSERT INTO drinks VALUE(17, "Mai-Tai", "30 ml Amber Jamaican Rum,30 ml Martinique Molasses Rhum,15 ml Orange Curacao,15 ml Orgeat Syrup (Almond),30 ml Fresh Lime Juice,7.5 ml Simple Syrup", "Add all ingredients into a shaker with ice. Shake and pour into a double rocks glass or a highball glass.  The Martinique molasses rum used by Trader Vic was not an Agricole rum but a type of “rummy” from molasses.");
INSERT INTO drinks VALUE(18, "Margarita", "50 ml Tequila 100%% Agave,20 ml Triple Sec,15 ml Freshly Squeezed Lime Juice", "Add all ingredients into a shaker with ice. Shake and strain into a chilled cocktail glass");
INSERT INTO drinks VALUE(19, "Mimosa", "75 ml Fresh orange juice,75 ml Prosecco", "Pour orange juice into a flute glass and gently pour the sparkling wine. Stir gently. Note: Also known as Buck's Fizz.");
INSERT INTO drinks VALUE(20, "Mint Julep", "60 ml Bourbon Whiskey,4 fresh Mint sprigs,1 tsp Powdered Sugar,2 tsp Water", "In Julep Stainless Steel Cup gently muddle the mint with sugar and water. Fill the glass with cracked ice, add the Bourbon and stir well until the cup frosts.");
INSERT INTO drinks VALUE(21, "Mojito", "45 ml White Cuban Ron,20 ml Fresh Lime Juice,6 pcs Mint Sprigs,2 tsp White Cane Sugar,Soda Water", "Mix mint springs with sugar and lime juice. Add splash of soda water and fill the glass with ice. Pour the rum and top with soda water. Light stir to involve all ingredients.");
INSERT INTO drinks VALUE(22, "Moscow Mule", "45 ml Smirnoff Vodka,120 ml Ginger Beer,10 ml Fresh lime juice", "In a Mule Cup or rocks glass, combine the vodka and ginger beer. Add lime juice and gently stir to involve all ingredients.");
INSERT INTO drinks VALUE(23, "Pina Colada", "50 ml White Rum,30 ml Coconut Cream,50 ml Fresh Pineapple Juice", "Blend all the ingredients with ice in an electric blender, pour into a large glass, and serve with straws.  Note: Historically a few drops of fresh lime juice were added to taste. 4 slices of fresh pineapple can be used instead of juice");
INSERT INTO drinks VALUE(24, "Pisco Sour", "60 ml Pisco,30 ml Fresh Lemon Juice,20 ml Simple Syrup,1 Raw Egg White", "Add all ingredients into a shaker with ice. Shake and strain into a chilled goblet glass.");
INSERT INTO drinks VALUE(25, "Sea Breeze", "40 ml Vodka,120 ml Cranberry Juice,30 ml Grapefruit Juice", "Build all ingredients in a highball glass filled with ice.");
INSERT INTO drinks VALUE(26, "Sex on the Beach", "40 ml Vodka,20 ml Peach Schnapps,40 ml Fresh Orange Juice,40 ml Cranberry Juice", "Build all ingredients in a highball glass filled with ice.");
INSERT INTO drinks VALUE(27, "Singapore Sling", "30 ml Gin,15 ml Cherry liqueur,7.5 ml Cointreau,7.5 ml DOM Bénédictine,120 ml Fresh Pineapple Juice,15 ml Fresh Lime Juice,10 ml Grenadine Syrup,A dash of Angostura bitters", "Pour all ingredients into a cocktail shaker filled with ice cubes. Shake well. Strain into Hurricane glass.");
INSERT INTO drinks VALUE(28, "Tequila Sunrise", "45 ml Tequila,90 ml Fresh Orange Juice,15 ml Grenadine Syrup", "Pour tequila and orange juice directly into highball glass filled with ice cubes. Add the grenadine syrup to create chromatic effect (sunrise), do not stir.");
INSERT INTO drinks VALUE(29, "Vesper", "45 ml Gin,15 ml Vodka,7.5 ml Lillet Blanc", "Pour all ingredients into a cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(30, "Zombie", "45 ml Jamaican dark rum,45 ml Gold Puerto Rican rum,30 ml Demerara Rum,20 ml Fresh lime juice,15 ml Falernum,15 ml Donn's Mix,1 tsp Grenadine syrup,1 dash Angostura bitters,6 drops Pernod", "Add all ingredients into an electric blender with 170 grams of cracked ice. With pulse bottom blend for a few seconds. Serve in a tall tumbler glass.  Note: Donn's Mix: 2 parts of fresh yellow grapefruit and 1 part of cinnamon syrup");
INSERT INTO drinks VALUE(31, "Barracuda", "45 ml Gold Rum,15 ml Galliano,60 ml Fresh Pineapple Juice,1 dash Fresh Lime Juice,Top up with Prosecco", "Pour all ingredients into cocktail shaker except the Prosecco, shake well with ice, strain into chilled highball glass filled with ice and top up with Prosecco.");
INSERT INTO drinks VALUE(32, "Bee's Knees", "52.5 ml Dry Gin,2 teaspoons Honey Syrup,22.5 ml Fresh Lemon Juice,22.5 ml Fresh Orange Juice", "Stir honey with lemon and orange juices until it dissolves, add gin and shake with ice. Strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(33, "Bramble", "50 ml Gin,25 ml Fresh Lemon Juice,12.5 ml Sugar Syrup,15 ml Crème de Mûre", "Pour all ingredients into a cocktail shaker except the Crème de Mûre, shake well with ice, strain into chilled old fashioned glass filled with crushed ice, then pour the blackberry liqueur (Crème de Mûre) over the top of the drink, in a circular motion.");
INSERT INTO drinks VALUE(34, "Canchanchara", "60 ml Cuban Aguardiente,15 ml Fresh Lime Juice,15 ml Raw Honey,50 ml Water", "Mix honey with water and lime juice and spread the mixture on the bottom and sides of the glass. Add cracked ice, and then the rum. End by energetically stirring from bottom to top.");
INSERT INTO drinks VALUE(35, "Dark ‘n' stormy", "60 ml Goslings Rum,100 ml Ginger Beer", "In a highball glass filled with ice pour the ginger beer and top floating with the Rum.");
INSERT INTO drinks VALUE(36, "Espresso Martini", "50 ml Vodka,30 ml Kahlúa,10 ml Sugar Syrup,1 strong Espresso", "Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(37, "Fernandito", "50 ml Fernet Branca,Fill up with Cola", "Pour the Fernet Branca into a double old fashioned glass with ice, fill the glass up with Cola. Gently stir.");
INSERT INTO drinks VALUE(38, "French Martini", "45 ml Vodka,15 ml Raspberry Liqueur,15 ml Fresh Pineapple Juice", "Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(39, "Illegal", "30 ml Espadin Mezcal,15 ml Jamaica Overproof White Rum,15 ml Falernum,1 Bar Spoon Maraschino Luxardo,22.5 ml Fresh Lime Juice,15 ml Simple Syrup,Few Drops of Egg White (Optional)", "Pour all ingredients into the shaker. Shake vigorously with ice. Strain into a chilled cocktail glass, or “on the rocks” in a traditional clay or terracotta mug.");
INSERT INTO drinks VALUE(40, "Lemon drop Martini", "30 ml Vodka Citron,20 ml Triple Sec,15 ml Fresh Lemon Juice", "Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(41, "Naked and Famous", "22.5 ml Mezcal,22.5 ml Yellow Chartreuse,22.5 ml Aperol,22.5 ml Fresh Lime Juice", "Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(42, "New York Sour", "60 ml Rye Whiskey or Bourbon,22.5 ml Simple syrup,30 ml Fresh lemon juice,Few Drops of Egg White,15 ml Red wine (Shiraz or Malbech)", "Pour all ingredients into the shaker. Shake vigorously with ice. Strain into a chilled rocks glass filled with ice. Float the wine on top.");
INSERT INTO drinks VALUE(43, "Old Cuban", "6/8 pcs Mint Leaves,45 ml Aged Rum,22.5 ml Fresh Lime Juice,30 ml Simple Syrup,2 Dashes Angostura Bitters,60 ml Brut Champagne or Prosecco", "Pour all ingredients into cocktail shaker except the wine, shake well with ice, strain into chilled elegant cocktail glass. Top up with the sparkling wine.");
INSERT INTO drinks VALUE(44, "Paloma", "50 ml 100%% Agave Tequila,5 ml Fresh lime,A pinch of Salt,100 ml Pink Grapefruit Soda", "Poor the tequila into a highball glass, squeeze the lime juice. Add ice and salt, fill up pink grapefruit soda. Stir gently.");
INSERT INTO drinks VALUE(45, "Paper Plane", "30 ml Bourbon Whiskey,30 ml Amaro Nonino,30 ml Aperol,30 ml Fresh Lemon Juice", "Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(46, "Penicillin", "60 ml Blended Scotch Whisky,7.5 ml Lagavulin 16 y Whisky,22.5 ml Fresh Lemon Juice,22.5 ml Honey Syrup,2-3 quarter size Sliced Fresh Ginger", "Muddle fresh ginger in a shaker and add the remaining ingredients, except for the Islay single malt whiskey. Fill the shaker with ice and shake. Double-strain into a chilled old fashioned glass with ice. Float the single malt whisky on top.");
INSERT INTO drinks VALUE(47, "Russian Spring Punch", "25 ml Vodka,25 ml Fresh Lemon Juice,15 ml Crème de Cassis,10 ml Sugar syrup,Top up Sparkling wine", "Pour all ingredients into a cocktail shaker except the sparkling wine, shake well with ice, strain into a chilled tall tumbler glass filled with ice, and top up with sparkling wine.");
INSERT INTO drinks VALUE(48, "Southside", "60 ml London Dry Gin,30 ml Fresh Lemon Juice,15 ml Simple Syrup,5/6 Mint Leaves,Few Drops of Egg White (Optional)", "Pour all ingredients into a cocktail shaker, shake well with ice, double-strain into chilled cocktail glass. Note: If egg white is used shake vigorously.");
INSERT INTO drinks VALUE(49, "Spicy Fifty", "50 ml Vodka Vanilla,15 ml Elderflower Cordial,15 ml Fresh Lime Juice,10 ml Monin Honey Syrup,2 thin Slices Red Chili Pepper", "Pour all ingredients into a cocktail shaker, shake well with ice, double-strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(50, "Spritz", "90 ml Prosecco,60 ml Aperol,Splash of Soda water", "Build all ingredients into a wine glass filled with ice. Stir gently. NOTE: There are other versions of the Spritz that use Campari, Cynar or Select instead of Aperol.");
INSERT INTO drinks VALUE(51, "Suffering Bastard", "30 ml Cognac or Brandy,30 ml Gin,15 ml Fresh Lime Juice,2 Dashes Angostura Bitters,Top up Ginger beer", "Pour all ingredients into a cocktail shaker except the ginger beer, shake well with ice, Pour unstrained into a Collins glass or in the original S. Bastard mug and top up with ginger beer.");
INSERT INTO drinks VALUE(52, "Tipperary", "50 ml Irish Whiskey,25 ml Sweet Red Vermouth,15 ml Green Chartreuse,2 Dashes Angostura Bitters", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.");
INSERT INTO drinks VALUE(53, "Tommy's Margarita", "60 ml Tequila Agave 100%% Reposado,30 ml Fresh Lime Juice (Persiano),30 ml Agave Syrup (1/2 Water + 1/2 Agave Nectar)", "Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled rocks glass filled with ice.");
INSERT INTO drinks VALUE(54, "Trinidad Sour", "45 ml Angostura Bitters,30 ml Orgeat Syrup,22.5 ml Fresh Lemon Juice,15 ml Rye Whisky", "Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(55, "VE.N.TO", "45 ml White Smooth Grappa,22.5 ml Fresh lemon Juice,15 ml Honey mix (replace water with chamomile),15 ml Chamomile cordial,10 ml Egg White (Optional)", "Pour all ingredients into the shaker. Shake vigorously with ice. Strain into a chilled small tumbler glass filled with ice. Notes: If desired water can be replaced by chamomile infusion in the honey mix.");
INSERT INTO drinks VALUE(56, "Yellow Bird", "30 ml White rum,15 ml Galliano,15 ml Triple Sec,15 ml Fresh Lime Juice", "Pour all ingredients into a cocktail shaker, shake well with ice, strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(57, "Alexander", "30 ml Cognac,30 ml Crème de Cacao (Brown),30 ml Fresh Cream", "Pour all ingredients into cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(58, "Americano", "30 ml Bitter Campari,30 ml Sweet Red Vermouth,A splash of Soda Water", "Mix the ingredients directly in an old fashioned glass filled with ice cubes. Add a splash of Soda Water. Stir gently.");
INSERT INTO drinks VALUE(59, "Angel Face", "30 ml Gin,30 ml Apricot Brandy,30 ml Calvados", "Pour all ingredients into cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(60, "Aviation", "45 ml Gin,15 ml Maraschino Luxardo,15 ml Fresh Lemon Juice,1 Bar Spoon Crème de Violette", "Add all ingredients into a cocktail shaker. Shake with cracked ice and strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(61, "Between the Sheets", "30 ml White Rum,30 ml Cognac,30 ml Triple Sec,20 ml Fresh Lemon Juice", "Add all ingredients into a cocktail shaker. Shake with ice and strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(62, "Boulevardier", "45 ml Bourbon or Rye Whiskey,30 ml Bitter Campari,30 ml Sweet Red Vermouth", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(63, "Brandy Crusta", "52.5 ml Brandy,7.5 ml Maraschino Luxardo,1 Bar Spoon Curacao,15 ml Fresh Lemon Juice,1 Bar Spoon Simple Syrup,2 Dashes Aromatic Bitters", "Mix together all ingredients with ice cubes in a mixing glass and strain into prepared slim cocktail glass.");
INSERT INTO drinks VALUE(64, "Casino", "40 ml Old Tom Gin,10 ml Maraschino Luxardo,10 ml Fresh Lemon Juice,2 Dashes Orange Bitters", "Pour all ingredients into cocktails shaker, shake well with ice, strain into chilled rocks glass with ice.");
INSERT INTO drinks VALUE(65, "Clover Club", "45 ml Gin,15 ml Raspberry Syrup,15 ml Fresh Lemon Juice,Few Drops of Egg White", "Pour all ingredients into cocktails shaker, shake well with ice, strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(66, "Daiquiri", "60 ml White Cuban Ron,20 ml Fresh Lime Juice,2 Bar Spoons Superfine Sugar", "In a cocktail shaker add all ingredients. Stir well to dissolve the sugar. Add ice and shake. Strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(67, "Dry Martini", "60 ml Gin,10 ml Dry Vermouth", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.");
INSERT INTO drinks VALUE(68, "Gin Fizz", "45 ml Gin,30 ml Fresh Lemon Juice,10 ml Simple Syrup,Splash of Soda Water", "Shake all ingredients with ice except soda water. Pour into thin tall Tumbler glass , top with a splash soda water.  NOTE: Serve without ice.");
INSERT INTO drinks VALUE(69, "Hanky Panky", "45 ml London Dry Gin,45 ml Sweet Red Vermouth,7.5 ml Fernet Branca", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(70, "John Collins", "45 ml Gin,30 ml Fresh Lemon Juice,15 ml Simple Syrup,60 ml Soda Water", "Pour all ingredients directly into a highball filled with ice. Stir gently. NOTE: Use ‘Old Tom' Gin for Tom Collins.");
INSERT INTO drinks VALUE(71, "Last word", "22.5 ml Gin,22.5 ml Green Chartreuse,22.5 ml Maraschino Luxardo,22.5 ml Fresh Lime Juice", "Add all ingredients into a cocktail shaker. Shake with ice and strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(72, "Manhattan", "50 ml Rye Whiskey,20 ml Sweet Red Vermouth,1 dash Angostura Bitters", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(73, "Martinez", "45 ml London Dry Gin,45 ml Sweet Red Vermouth,1 Bar Spoon Maraschino Liqueur,2 Dashes Orange Bitters", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(74, "Mary Pickford", "45 ml White Rum,45 ml Fresh Pineapple Juice,7.5 ml Maraschino Luxardo,5 ml Grenadine Syrup", "Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(75, "Monkey Gland", "45 ml Dry Gin,45 ml Fresh Orange Juice,1 Table Spoon Absinthe,1 Table Spoon Grenadine Syrup", "Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(76, "Negroni", "30 ml Gin,30 ml Bitter Campari,30 ml Sweet Red Vermouth", "Pour all ingredients directly into a chilled old fashioned glass filled with ice, Stir gently.");
INSERT INTO drinks VALUE(77, "Old Fashioned", "45 ml Bourbon or Rye Whiskey,1 Sugar Cube,Few Dashes Angostura Bitters,Few Dashes Plain Water", "Place sugar cube in old fashioned glass and saturate with bitter, add few dashes of plain water. Muddle until dissolved. Fill the glass with ice cubes and add whiskey. Stir gently.");
INSERT INTO drinks VALUE(78, "Paradise", "30 ml Gin,20 ml Apricot Brandy,15 ml Fresh Orange Juice", "Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.");
INSERT INTO drinks VALUE(79, "Planter's Punch", "45 ml Jamaican Rum,15 ml Lime Juice,30 ml Sugar Cane Juice", "Pour all ingredients directly in a small tumbler or a typical terracotta glass. NOTE: Add dilution up to taste, it can be given by water, ice or fresh juices.");
INSERT INTO drinks VALUE(80, "Porto Flip", "15 ml Brandy,45 ml Red Tawny Port Wine,10 ml Egg Yolk", "Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(81, "Ramos Fizz", "45 ml Gin,15 ml Fresh Lime Juice,15 ml Fresh Lemon Juice,30 ml Sugar Syrup,60 ml Cream,30 ml Egg white,3 Dashes Orange Flower Water,2 Drops Vanilla Extract,Soda Water", "Pour all ingredients except soda water in a cocktail shaker with ice, Shake for two minutes, double strain in a glass, pour the drink back in the shaker, and hard shake without ice for one minute. Strain into a highball glass, top up with soda. NOTE: The drink was invented by Henry Ramos in 1888, at his bar Meyer's Table d'Hôtel Internationale in New Orleans. The Ramos Fizz was originally shaken for 12 minutes by a crew of 30 bartenders who passed the shaker from one to another.");
INSERT INTO drinks VALUE(82, "Rusty Nail", "45 ml Scotch Whisky,25 ml Drambuie", "Pour all ingredients directly into an old fashioned glass filled with ice. Stir gently.");
INSERT INTO drinks VALUE(83, "Sazerac", "50 ml Cognac,10 ml Absinthe,1 Sugar Cube,2 Dashes Peychaud's Bitters", "Rinse a chilled old-fashioned glass with the absinthe, add crushed ice and set it aside. Stir the remaining ingredients over ice in a mixing glass. Discard the ice and any excess absinthe from the prepared glass, strain the mixed drink into the glass.  NOTE: The original recipe changed after the American Civil War, Rye Whiskey substituted Cognac as it became hard to obtain.");
INSERT INTO drinks VALUE(84, "Sidecar", "50 ml Cognac,20 ml Triple Sec,20 ml Fresh Lemon Juice", "Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(85, "Stinger", "50 ml Cognac,20 ml White Crème de Menthe", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.");
INSERT INTO drinks VALUE(86, "Tuxedo", "30 ml Old Tom Gin,30 ml Dry Vermouth,1/2 Bar Spoon Maraschino Luxardo,1/4 Bar Spoon of Absinthe,3 Dashes Orange Bitters", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.");
INSERT INTO drinks VALUE(87, "Vieux Carrè", "30 ml Rye Whiskey,30 ml Cognac,30 ml Sweet Vermouth,1 Bar Spoon Bénédictine,2 Dashes Peychaud's Bitters", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.");
INSERT INTO drinks VALUE(88, "Whiskey Sour", "45 ml Bourbon Whiskey,25 ml Fresh Lemon Juice,20 ml Sugar Syrup,20 ml Egg White (Optional)", "Pour all ingredients into a cocktail shaker filled with ice. Shake well. Strain into cobbler glass. If served “On the rocks”, strain ingredients into an old fashioned glass filled with ice.  NOTE: If egg white is used shake little harder to release and incorporate the foam from the egg white.");
INSERT INTO drinks VALUE(89, "White Lady", "40 ml Gin,30 ml Triple Sec,20 ml Fresh Lemon Juice", "Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.");

INSERT INTO ingredients VALUE(0, "Prosecco");
INSERT INTO ingredients VALUE(0, "White Peach Puree");
INSERT INTO ingredients VALUE(1, "Vodka");
INSERT INTO ingredients VALUE(1, "Coffee Liqueur");
INSERT INTO ingredients VALUE(2, "Vodka");
INSERT INTO ingredients VALUE(2, "Tomato Juice");
INSERT INTO ingredients VALUE(2, "Lemon");
INSERT INTO ingredients VALUE(2, "Worcestershire Sauce");
INSERT INTO ingredients VALUE(2, "Tabasco");
INSERT INTO ingredients VALUE(2, "Celery Salt");
INSERT INTO ingredients VALUE(2, "Pepper");
INSERT INTO ingredients VALUE(3, "Cachaça");
INSERT INTO ingredients VALUE(3, "Lime");
INSERT INTO ingredients VALUE(3, "White Cane Sugar");
INSERT INTO ingredients VALUE(4, "Champagne");
INSERT INTO ingredients VALUE(4, "Cognac");
INSERT INTO ingredients VALUE(4, "Angostura bitters");
INSERT INTO ingredients VALUE(4, "Grand Marnier");
INSERT INTO ingredients VALUE(4, "Sugar Cube");
INSERT INTO ingredients VALUE(5, "Gin");
INSERT INTO ingredients VALUE(5, "Cointreau");
INSERT INTO ingredients VALUE(5, "Lillet Blanc");
INSERT INTO ingredients VALUE(5, "Lemon");
INSERT INTO ingredients VALUE(5, "Absinthe");
INSERT INTO ingredients VALUE(6, "Vodka Citron");
INSERT INTO ingredients VALUE(6, "Cointreau");
INSERT INTO ingredients VALUE(6, "Lime");
INSERT INTO ingredients VALUE(6, "Cranberry Juice");
INSERT INTO ingredients VALUE(7, "White Rum");
INSERT INTO ingredients VALUE(7, "Coca Cola");
INSERT INTO ingredients VALUE(7, "Lime");
INSERT INTO ingredients VALUE(8, "Gin");
INSERT INTO ingredients VALUE(8, "Lemon");
INSERT INTO ingredients VALUE(8, "Sugar Syrup");
INSERT INTO ingredients VALUE(8, "Champagne");
INSERT INTO ingredients VALUE(9, "Cognac");
INSERT INTO ingredients VALUE(9, "Amaretto");
INSERT INTO ingredients VALUE(10, "Galliano");
INSERT INTO ingredients VALUE(10, "Triple Sec");
INSERT INTO ingredients VALUE(10, "Fresh Orange Juice");
INSERT INTO ingredients VALUE(10, "Fresh Cream");
INSERT INTO ingredients VALUE(11, "Crème de Cacao");
INSERT INTO ingredients VALUE(11, "Crème de Menthe");
INSERT INTO ingredients VALUE(11, "Fresh Cream");
INSERT INTO ingredients VALUE(12, "Rum");
INSERT INTO ingredients VALUE(12, "Grapefruit Juice");
INSERT INTO ingredients VALUE(12, "Maraschino Luxardo");
INSERT INTO ingredients VALUE(12, "Lime");
INSERT INTO ingredients VALUE(13, "Cognac");
INSERT INTO ingredients VALUE(13, "Ginger Ale");
INSERT INTO ingredients VALUE(13, "Angostura Bitters");
INSERT INTO ingredients VALUE(14, "Irish Whiskey");
INSERT INTO ingredients VALUE(14, "Hot coffee");
INSERT INTO ingredients VALUE(14, "Fresh cream");
INSERT INTO ingredients VALUE(14, "Sugar");
INSERT INTO ingredients VALUE(15, "Dry White Wine");
INSERT INTO ingredients VALUE(15, "Crème de Cassis");
INSERT INTO ingredients VALUE(16, "Vodka");
INSERT INTO ingredients VALUE(16, "Tequila");
INSERT INTO ingredients VALUE(16, "White rum");
INSERT INTO ingredients VALUE(16, "Gin");
INSERT INTO ingredients VALUE(16, "Cointreau");
INSERT INTO ingredients VALUE(16, "Lemon");
INSERT INTO ingredients VALUE(16, "Simple syrup");
INSERT INTO ingredients VALUE(16, "Cola");
INSERT INTO ingredients VALUE(17, "Amber Jamaican Rum");
INSERT INTO ingredients VALUE(17, "Martinique Molasses Rhum");
INSERT INTO ingredients VALUE(17, "Orange Curacao");
INSERT INTO ingredients VALUE(17, "Orgeat Syrup");
INSERT INTO ingredients VALUE(17, "Lime");
INSERT INTO ingredients VALUE(17, "Simple Syrup");
INSERT INTO ingredients VALUE(18, "Tequila");
INSERT INTO ingredients VALUE(18, "Triple Sec");
INSERT INTO ingredients VALUE(18, "Lime");
INSERT INTO ingredients VALUE(19, "Fresh orange juice");
INSERT INTO ingredients VALUE(19, "Prosecco");
INSERT INTO ingredients VALUE(20, "Bourbon Whiskey");
INSERT INTO ingredients VALUE(20, "fresh Mint sprigs");
INSERT INTO ingredients VALUE(20, "Powdered Sugar");
INSERT INTO ingredients VALUE(20, "Water");
INSERT INTO ingredients VALUE(21, "White Cuban Ron");
INSERT INTO ingredients VALUE(21, "Lime");
INSERT INTO ingredients VALUE(21, "Mint Sprigs");
INSERT INTO ingredients VALUE(21, "White Cane Sugar");
INSERT INTO ingredients VALUE(21, "Soda Water");
INSERT INTO ingredients VALUE(22, "Vodka");
INSERT INTO ingredients VALUE(22, "Ginger Beer");
INSERT INTO ingredients VALUE(22, "Lime");
INSERT INTO ingredients VALUE(23, "White Rum");
INSERT INTO ingredients VALUE(23, "Coconut Cream");
INSERT INTO ingredients VALUE(23, "Fresh Pineapple Juice");
INSERT INTO ingredients VALUE(24, "Pisco");
INSERT INTO ingredients VALUE(24, "Lemon");
INSERT INTO ingredients VALUE(24, "Simple Syrup");
INSERT INTO ingredients VALUE(24, "Raw Egg White");
INSERT INTO ingredients VALUE(25, "Vodka");
INSERT INTO ingredients VALUE(25, "Cranberry Juice");
INSERT INTO ingredients VALUE(25, "Grapefruit Juice");
INSERT INTO ingredients VALUE(26, "Vodka");
INSERT INTO ingredients VALUE(26, "Peach Schnapps");
INSERT INTO ingredients VALUE(26, "Fresh Orange Juice");
INSERT INTO ingredients VALUE(26, "Cranberry Juice");
INSERT INTO ingredients VALUE(27, "Gin");
INSERT INTO ingredients VALUE(27, "Cherry liqueur");
INSERT INTO ingredients VALUE(27, "Cointreau");
INSERT INTO ingredients VALUE(27, "DOM Bénédictine");
INSERT INTO ingredients VALUE(27, "Fresh Pineapple Juice");
INSERT INTO ingredients VALUE(27, "Lime");
INSERT INTO ingredients VALUE(27, "Grenadine Syrup");
INSERT INTO ingredients VALUE(27, "Angostura bitters");
INSERT INTO ingredients VALUE(28, "Tequila");
INSERT INTO ingredients VALUE(28, "Fresh Orange Juice");
INSERT INTO ingredients VALUE(28, "Grenadine Syrup");
INSERT INTO ingredients VALUE(29, "Gin");
INSERT INTO ingredients VALUE(29, "Vodka");
INSERT INTO ingredients VALUE(29, "Lillet Blanc");
INSERT INTO ingredients VALUE(30, "Jamaican dark rum");
INSERT INTO ingredients VALUE(30, "Gold Puerto Rican rum");
INSERT INTO ingredients VALUE(30, "Demerara Rum");
INSERT INTO ingredients VALUE(30, "Lime");
INSERT INTO ingredients VALUE(30, "Falernum");
INSERT INTO ingredients VALUE(30, "Donn's Mix");
INSERT INTO ingredients VALUE(30, "Grenadine syrup");
INSERT INTO ingredients VALUE(30, "Angostura bitters");
INSERT INTO ingredients VALUE(30, "Pernod");
INSERT INTO ingredients VALUE(31, "Gold Rum");
INSERT INTO ingredients VALUE(31, "Galliano");
INSERT INTO ingredients VALUE(31, "Fresh Pineapple Juice");
INSERT INTO ingredients VALUE(31, "Lime");
INSERT INTO ingredients VALUE(31, "Prosecco");
INSERT INTO ingredients VALUE(32, "Dry Gin");
INSERT INTO ingredients VALUE(32, "Honey Syrup");
INSERT INTO ingredients VALUE(32, "Lemon");
INSERT INTO ingredients VALUE(32, "Fresh Orange Juice");
INSERT INTO ingredients VALUE(33, "Gin");
INSERT INTO ingredients VALUE(33, "Lemon");
INSERT INTO ingredients VALUE(33, "Sugar Syrup");
INSERT INTO ingredients VALUE(33, "Crème de Mûre");
INSERT INTO ingredients VALUE(34, "Cuban Aguardiente");
INSERT INTO ingredients VALUE(34, "Lime");
INSERT INTO ingredients VALUE(34, "Raw Honey");
INSERT INTO ingredients VALUE(34, "Water");
INSERT INTO ingredients VALUE(35, "Goslings Rum");
INSERT INTO ingredients VALUE(35, "Ginger Beer");
INSERT INTO ingredients VALUE(36, "Vodka");
INSERT INTO ingredients VALUE(36, "Kahlúa");
INSERT INTO ingredients VALUE(36, "Sugar Syrup");
INSERT INTO ingredients VALUE(36, "strong Espresso");
INSERT INTO ingredients VALUE(37, "Fernet Branca");
INSERT INTO ingredients VALUE(37, "Cola");
INSERT INTO ingredients VALUE(38, "Vodka");
INSERT INTO ingredients VALUE(38, "Raspberry Liqueur");
INSERT INTO ingredients VALUE(38, "Fresh Pineapple Juice");
INSERT INTO ingredients VALUE(39, "Espadin Mezcal");
INSERT INTO ingredients VALUE(39, "Jamaica Overproof White Rum");
INSERT INTO ingredients VALUE(39, "Falernum");
INSERT INTO ingredients VALUE(39, "Maraschino Luxardo");
INSERT INTO ingredients VALUE(39, "Lime");
INSERT INTO ingredients VALUE(39, "Simple Syrup");
INSERT INTO ingredients VALUE(39, "Egg White");
INSERT INTO ingredients VALUE(40, "Vodka Citron");
INSERT INTO ingredients VALUE(40, "Triple Sec");
INSERT INTO ingredients VALUE(40, "Lemon");
INSERT INTO ingredients VALUE(41, "Mezcal");
INSERT INTO ingredients VALUE(41, "Yellow Chartreuse");
INSERT INTO ingredients VALUE(41, "Aperol");
INSERT INTO ingredients VALUE(41, "Lime");
INSERT INTO ingredients VALUE(42, "Rye Whiskey or Bourbon");
INSERT INTO ingredients VALUE(42, "Simple syrup");
INSERT INTO ingredients VALUE(42, "Lemon");
INSERT INTO ingredients VALUE(42, "Egg White");
INSERT INTO ingredients VALUE(42, "Red wine");
INSERT INTO ingredients VALUE(43, "Mint Leaves");
INSERT INTO ingredients VALUE(43, "Aged Rum");
INSERT INTO ingredients VALUE(43, "Lime");
INSERT INTO ingredients VALUE(43, "Simple Syrup");
INSERT INTO ingredients VALUE(43, "Angostura Bitters");
INSERT INTO ingredients VALUE(43, "Champagne");
INSERT INTO ingredients VALUE(44, "Tequila");
INSERT INTO ingredients VALUE(44, "Lime");
INSERT INTO ingredients VALUE(44, "Salt");
INSERT INTO ingredients VALUE(44, "Pink Grapefruit Soda");
INSERT INTO ingredients VALUE(45, "Bourbon Whiskey");
INSERT INTO ingredients VALUE(45, "Amaro Nonino");
INSERT INTO ingredients VALUE(45, "Aperol");
INSERT INTO ingredients VALUE(45, "Lemon");
INSERT INTO ingredients VALUE(46, "Blended Scotch Whisky");
INSERT INTO ingredients VALUE(46, "Lagavulin 16 y Whisky");
INSERT INTO ingredients VALUE(46, "Lemon");
INSERT INTO ingredients VALUE(46, "Honey Syrup");
INSERT INTO ingredients VALUE(46, "quarter size Sliced Fresh Ginger");
INSERT INTO ingredients VALUE(47, "Vodka");
INSERT INTO ingredients VALUE(47, "Lemon");
INSERT INTO ingredients VALUE(47, "Crème de Cassis");
INSERT INTO ingredients VALUE(47, "Sugar syrup");
INSERT INTO ingredients VALUE(47, "Sparkling wine");
INSERT INTO ingredients VALUE(48, "London Dry Gin");
INSERT INTO ingredients VALUE(48, "Lemon");
INSERT INTO ingredients VALUE(48, "Simple Syrup");
INSERT INTO ingredients VALUE(48, "Mint Leaves");
INSERT INTO ingredients VALUE(48, "Egg White");
INSERT INTO ingredients VALUE(49, "Vodka Vanilla");
INSERT INTO ingredients VALUE(49, "Elderflower Cordial");
INSERT INTO ingredients VALUE(49, "Lime");
INSERT INTO ingredients VALUE(49, "Monin Honey Syrup");
INSERT INTO ingredients VALUE(49, "thin Slices Red Chili Pepper");
INSERT INTO ingredients VALUE(50, "Prosecco");
INSERT INTO ingredients VALUE(50, "Aperol");
INSERT INTO ingredients VALUE(50, "Soda water");
INSERT INTO ingredients VALUE(51, "Cognac or Brandy");
INSERT INTO ingredients VALUE(51, "Gin");
INSERT INTO ingredients VALUE(51, "Lime");
INSERT INTO ingredients VALUE(51, "Angostura Bitters");
INSERT INTO ingredients VALUE(51, "Ginger beer");
INSERT INTO ingredients VALUE(52, "Irish Whiskey");
INSERT INTO ingredients VALUE(52, "Sweet Red Vermouth");
INSERT INTO ingredients VALUE(52, "Green Chartreuse");
INSERT INTO ingredients VALUE(52, "Angostura Bitters");
INSERT INTO ingredients VALUE(53, "Tequila");
INSERT INTO ingredients VALUE(53, "Lime");
INSERT INTO ingredients VALUE(53, "Agave Syrup");
INSERT INTO ingredients VALUE(54, "Angostura Bitters");
INSERT INTO ingredients VALUE(54, "Orgeat Syrup");
INSERT INTO ingredients VALUE(54, "Lemon");
INSERT INTO ingredients VALUE(54, "Rye Whisky");
INSERT INTO ingredients VALUE(55, "White Smooth Grappa");
INSERT INTO ingredients VALUE(55, "Lemon");
INSERT INTO ingredients VALUE(55, "Honey mix");
INSERT INTO ingredients VALUE(55, "Chamomile cordial");
INSERT INTO ingredients VALUE(55, "Egg White");
INSERT INTO ingredients VALUE(56, "White rum");
INSERT INTO ingredients VALUE(56, "Galliano");
INSERT INTO ingredients VALUE(56, "Triple Sec");
INSERT INTO ingredients VALUE(56, "Lime");
INSERT INTO ingredients VALUE(57, "Cognac");
INSERT INTO ingredients VALUE(57, "Crème de Cacao");
INSERT INTO ingredients VALUE(57, "Fresh Cream");
INSERT INTO ingredients VALUE(58, "Bitter Campari");
INSERT INTO ingredients VALUE(58, "Sweet Red Vermouth");
INSERT INTO ingredients VALUE(58, "Soda Water");
INSERT INTO ingredients VALUE(59, "Gin");
INSERT INTO ingredients VALUE(59, "Apricot Brandy");
INSERT INTO ingredients VALUE(59, "Calvados");
INSERT INTO ingredients VALUE(60, "Gin");
INSERT INTO ingredients VALUE(60, "Maraschino Luxardo");
INSERT INTO ingredients VALUE(60, "Lemon");
INSERT INTO ingredients VALUE(60, "Crème de Violette");
INSERT INTO ingredients VALUE(61, "White Rum");
INSERT INTO ingredients VALUE(61, "Cognac");
INSERT INTO ingredients VALUE(61, "Triple Sec");
INSERT INTO ingredients VALUE(61, "Lemon");
INSERT INTO ingredients VALUE(62, "Bourbon or Rye Whiskey");
INSERT INTO ingredients VALUE(62, "Bitter Campari");
INSERT INTO ingredients VALUE(62, "Sweet Red Vermouth");
INSERT INTO ingredients VALUE(63, "Brandy");
INSERT INTO ingredients VALUE(63, "Maraschino Luxardo");
INSERT INTO ingredients VALUE(63, "Curacao");
INSERT INTO ingredients VALUE(63, "Lemon");
INSERT INTO ingredients VALUE(63, "Simple Syrup");
INSERT INTO ingredients VALUE(63, "Aromatic Bitters");
INSERT INTO ingredients VALUE(64, "Old Tom Gin");
INSERT INTO ingredients VALUE(64, "Maraschino Luxardo");
INSERT INTO ingredients VALUE(64, "Lemon");
INSERT INTO ingredients VALUE(64, "Orange Bitters");
INSERT INTO ingredients VALUE(65, "Gin");
INSERT INTO ingredients VALUE(65, "Raspberry Syrup");
INSERT INTO ingredients VALUE(65, "Lemon");
INSERT INTO ingredients VALUE(65, "Egg White");
INSERT INTO ingredients VALUE(66, "White Cuban Ron");
INSERT INTO ingredients VALUE(66, "Lime");
INSERT INTO ingredients VALUE(66, "Superfine Sugar");
INSERT INTO ingredients VALUE(67, "Gin");
INSERT INTO ingredients VALUE(67, "Dry Vermouth");
INSERT INTO ingredients VALUE(68, "Gin");
INSERT INTO ingredients VALUE(68, "Lemon");
INSERT INTO ingredients VALUE(68, "Simple Syrup");
INSERT INTO ingredients VALUE(68, "Soda Water");
INSERT INTO ingredients VALUE(69, "London Dry Gin");
INSERT INTO ingredients VALUE(69, "Sweet Red Vermouth");
INSERT INTO ingredients VALUE(69, "Fernet Branca");
INSERT INTO ingredients VALUE(70, "Gin");
INSERT INTO ingredients VALUE(70, "Lemon");
INSERT INTO ingredients VALUE(70, "Simple Syrup");
INSERT INTO ingredients VALUE(70, "Soda Water");
INSERT INTO ingredients VALUE(71, "Gin");
INSERT INTO ingredients VALUE(71, "Green Chartreuse");
INSERT INTO ingredients VALUE(71, "Maraschino Luxardo");
INSERT INTO ingredients VALUE(71, "Lime");
INSERT INTO ingredients VALUE(72, "Rye Whiskey");
INSERT INTO ingredients VALUE(72, "Sweet Red Vermouth");
INSERT INTO ingredients VALUE(72, "Angostura Bitters");
INSERT INTO ingredients VALUE(73, "London Dry Gin");
INSERT INTO ingredients VALUE(73, "Sweet Red Vermouth");
INSERT INTO ingredients VALUE(73, "Maraschino Liqueur");
INSERT INTO ingredients VALUE(73, "Orange Bitters");
INSERT INTO ingredients VALUE(74, "White Rum");
INSERT INTO ingredients VALUE(74, "Fresh Pineapple Juice");
INSERT INTO ingredients VALUE(74, "Maraschino Luxardo");
INSERT INTO ingredients VALUE(74, "Grenadine Syrup");
INSERT INTO ingredients VALUE(75, "Dry Gin");
INSERT INTO ingredients VALUE(75, "Fresh Orange Juice");
INSERT INTO ingredients VALUE(75, "Absinthe");
INSERT INTO ingredients VALUE(75, "Grenadine Syrup");
INSERT INTO ingredients VALUE(76, "Gin");
INSERT INTO ingredients VALUE(76, "Bitter Campari");
INSERT INTO ingredients VALUE(76, "Sweet Red Vermouth");
INSERT INTO ingredients VALUE(77, "Bourbon or Rye Whiskey");
INSERT INTO ingredients VALUE(77, "Sugar Cube");
INSERT INTO ingredients VALUE(77, "Angostura Bitters");
INSERT INTO ingredients VALUE(77, "Plain Water");
INSERT INTO ingredients VALUE(78, "Gin");
INSERT INTO ingredients VALUE(78, "Apricot Brandy");
INSERT INTO ingredients VALUE(78, "Fresh Orange Juice");
INSERT INTO ingredients VALUE(79, "Jamaican Rum");
INSERT INTO ingredients VALUE(79, "Lime");
INSERT INTO ingredients VALUE(79, "Sugar Cane Juice");
INSERT INTO ingredients VALUE(80, "Brandy");
INSERT INTO ingredients VALUE(80, "Red Tawny Port Wine");
INSERT INTO ingredients VALUE(80, "Egg Yolk");
INSERT INTO ingredients VALUE(81, "Gin");
INSERT INTO ingredients VALUE(81, "Lime");
INSERT INTO ingredients VALUE(81, "Lemon");
INSERT INTO ingredients VALUE(81, "Sugar Syrup");
INSERT INTO ingredients VALUE(81, "Cream");
INSERT INTO ingredients VALUE(81, "Egg white");
INSERT INTO ingredients VALUE(81, "Orange Flower Water");
INSERT INTO ingredients VALUE(81, "Vanilla Extract");
INSERT INTO ingredients VALUE(81, "Soda Water");
INSERT INTO ingredients VALUE(82, "Scotch Whisky");
INSERT INTO ingredients VALUE(82, "Drambuie");
INSERT INTO ingredients VALUE(83, "Cognac");
INSERT INTO ingredients VALUE(83, "Absinthe");
INSERT INTO ingredients VALUE(83, "Sugar Cube");
INSERT INTO ingredients VALUE(83, "Peychaud's Bitters");
INSERT INTO ingredients VALUE(84, "Cognac");
INSERT INTO ingredients VALUE(84, "Triple Sec");
INSERT INTO ingredients VALUE(84, "Lemon");
INSERT INTO ingredients VALUE(85, "Cognac");
INSERT INTO ingredients VALUE(85, "White Crème de Menthe");
INSERT INTO ingredients VALUE(86, "Old Tom Gin");
INSERT INTO ingredients VALUE(86, "Dry Vermouth");
INSERT INTO ingredients VALUE(86, "Maraschino Luxardo");
INSERT INTO ingredients VALUE(86, "Absinthe");
INSERT INTO ingredients VALUE(86, "Orange Bitters");
INSERT INTO ingredients VALUE(87, "Rye Whiskey");
INSERT INTO ingredients VALUE(87, "Cognac");
INSERT INTO ingredients VALUE(87, "Sweet Vermouth");
INSERT INTO ingredients VALUE(87, "Bénédictine");
INSERT INTO ingredients VALUE(87, "Peychaud's Bitters");
INSERT INTO ingredients VALUE(88, "Bourbon Whiskey");
INSERT INTO ingredients VALUE(88, "Lemon");
INSERT INTO ingredients VALUE(88, "Sugar Syrup");
INSERT INTO ingredients VALUE(88, "Egg White");
INSERT INTO ingredients VALUE(89, "Gin");
INSERT INTO ingredients VALUE(89, "Triple Sec");
INSERT INTO ingredients VALUE(89, "Lemon");

INSERT INTO ratings VALUE(0, 0, 0);
INSERT INTO ratings VALUE(1, 0, 0);
INSERT INTO ratings VALUE(2, 0, 0);
INSERT INTO ratings VALUE(3, 0, 0);
INSERT INTO ratings VALUE(4, 0, 0);
INSERT INTO ratings VALUE(5, 0, 0);
INSERT INTO ratings VALUE(6, 0, 0);
INSERT INTO ratings VALUE(7, 0, 0);
INSERT INTO ratings VALUE(8, 0, 0);
INSERT INTO ratings VALUE(9, 0, 0);
INSERT INTO ratings VALUE(10, 0, 0);
INSERT INTO ratings VALUE(11, 0, 0);
INSERT INTO ratings VALUE(12, 0, 0);
INSERT INTO ratings VALUE(13, 0, 0);
INSERT INTO ratings VALUE(14, 0, 0);
INSERT INTO ratings VALUE(15, 0, 0);
INSERT INTO ratings VALUE(16, 0, 0);
INSERT INTO ratings VALUE(17, 0, 0);
INSERT INTO ratings VALUE(18, 0, 0);
INSERT INTO ratings VALUE(19, 0, 0);
INSERT INTO ratings VALUE(20, 0, 0);
INSERT INTO ratings VALUE(21, 0, 0);
INSERT INTO ratings VALUE(22, 0, 0);
INSERT INTO ratings VALUE(23, 0, 0);
INSERT INTO ratings VALUE(24, 0, 0);
INSERT INTO ratings VALUE(25, 0, 0);
INSERT INTO ratings VALUE(26, 0, 0);
INSERT INTO ratings VALUE(27, 0, 0);
INSERT INTO ratings VALUE(28, 0, 0);
INSERT INTO ratings VALUE(29, 0, 0);
INSERT INTO ratings VALUE(30, 0, 0);
INSERT INTO ratings VALUE(31, 0, 0);
INSERT INTO ratings VALUE(32, 0, 0);
INSERT INTO ratings VALUE(33, 0, 0);
INSERT INTO ratings VALUE(34, 0, 0);
INSERT INTO ratings VALUE(35, 0, 0);
INSERT INTO ratings VALUE(36, 0, 0);
INSERT INTO ratings VALUE(37, 0, 0);
INSERT INTO ratings VALUE(38, 0, 0);
INSERT INTO ratings VALUE(39, 0, 0);
INSERT INTO ratings VALUE(40, 0, 0);
INSERT INTO ratings VALUE(41, 0, 0);
INSERT INTO ratings VALUE(42, 0, 0);
INSERT INTO ratings VALUE(43, 0, 0);
INSERT INTO ratings VALUE(44, 0, 0);
INSERT INTO ratings VALUE(45, 0, 0);
INSERT INTO ratings VALUE(46, 0, 0);
INSERT INTO ratings VALUE(47, 0, 0);
INSERT INTO ratings VALUE(48, 0, 0);
INSERT INTO ratings VALUE(49, 0, 0);
INSERT INTO ratings VALUE(50, 0, 0);
INSERT INTO ratings VALUE(51, 0, 0);
INSERT INTO ratings VALUE(52, 0, 0);
INSERT INTO ratings VALUE(53, 0, 0);
INSERT INTO ratings VALUE(54, 0, 0);
INSERT INTO ratings VALUE(55, 0, 0);
INSERT INTO ratings VALUE(56, 0, 0);
INSERT INTO ratings VALUE(57, 0, 0);
INSERT INTO ratings VALUE(58, 0, 0);
INSERT INTO ratings VALUE(59, 0, 0);
INSERT INTO ratings VALUE(60, 0, 0);
INSERT INTO ratings VALUE(61, 0, 0);
INSERT INTO ratings VALUE(62, 0, 0);
INSERT INTO ratings VALUE(63, 0, 0);
INSERT INTO ratings VALUE(64, 0, 0);
INSERT INTO ratings VALUE(65, 0, 0);
INSERT INTO ratings VALUE(66, 0, 0);
INSERT INTO ratings VALUE(67, 0, 0);
INSERT INTO ratings VALUE(68, 0, 0);
INSERT INTO ratings VALUE(69, 0, 0);
INSERT INTO ratings VALUE(70, 0, 0);
INSERT INTO ratings VALUE(71, 0, 0);
INSERT INTO ratings VALUE(72, 0, 0);
INSERT INTO ratings VALUE(73, 0, 0);
INSERT INTO ratings VALUE(74, 0, 0);
INSERT INTO ratings VALUE(75, 0, 0);
INSERT INTO ratings VALUE(76, 0, 0);
INSERT INTO ratings VALUE(77, 0, 0);
INSERT INTO ratings VALUE(78, 0, 0);
INSERT INTO ratings VALUE(79, 0, 0);
INSERT INTO ratings VALUE(80, 0, 0);
INSERT INTO ratings VALUE(81, 0, 0);
INSERT INTO ratings VALUE(82, 0, 0);
INSERT INTO ratings VALUE(83, 0, 0);
INSERT INTO ratings VALUE(84, 0, 0);
INSERT INTO ratings VALUE(85, 0, 0);
INSERT INTO ratings VALUE(86, 0, 0);
INSERT INTO ratings VALUE(87, 0, 0);
INSERT INTO ratings VALUE(88, 0, 0);
INSERT INTO ratings VALUE(89, 0, 0);